DATO  	EQU 0X21
COUNTY 	EQU 0X22
COUNTMINIX 	EQU 0X23
LIMITY 	EQU 0X24
LIMITMINIX 	EQU 0X25
P1	EQU 0X26
P2    	EQU 0X27
COUNTX EQU 0X28
LIMITX EQU 0X29
VARMAXX	EQU	0X30
VARMAXY	EQU	0X31
varA EQU 0x32
varB EQU 0x33
varC EQU 0x34
varE EQU 0x35
cont EQU 0x36 


INICIO

	ORG		0X00
	GOTO	START
;--------------------DEFINIR ENTRADAS Y SALIDAS-----------------------
START
	;En los puertos: 1 -> entra | 0 -> sale
	;BIT SET FILE
	BSF 	STATUS, 5	; COLOCAMOS 1 EN EL BIT 5 DE REG. ESTATUS
	CLRF	TRISB		;Todo B es salida
	CLRF	TRISD		;Todo D es salida
	BCF	STATUS, RP0	;TODOS LOS PINES DE B SON SALIDAS
;----------------INICIALIZAR VARIABLES -------------------------------
	
	
	MOVLW	0X00
	MOVWF 	PORTB  		;SET 0 a todas las patas del puerto B
	MOVLW	0X00
	MOVWF 	PORTD  		;SET 0 a todas las patas del puerto D
	MOVLW 	0xFF		;255	
	MOVWF 	LIMITY 		;LIMITY = 255	12|10 
	MOVLW 	0x20		;32	2|0
	MOVWF 	LIMITMINIX		;LIMITMINIX = 32	2|0
	MOVLW	0x10		;16	1|0
	MOVWF	LIMITX	;LIMITX = 16	1|0
	CALL 	LIMPIARY		;CONTADORY = 0
	CALL 	LIMPIARMINIX		;CONTADORMINIX = 0
	CALL 	LIMIPIARX	;CONTADORx = 0
;--------------------------- MAIN -----------------------------------
					
MAIN

	CALL	CICLOMINIX		;Mover en x, analizar y, regresar en y 
	INCF	COUNTX,1	;COUNTX++
	MOVF	LIMITX, W	;W = LIMITX
	SUBWF	COUNTX, w	;W = LIMITX - COUNTX
	BTFSS	STATUS,Z	;SALTO SI LA RESTA DIO 0
	GOTO	MAIN		;REPETIR HASTA QUE COUNTX = LIMITX
	CALL	LIMIPIARX	;COUNTX = 0
	CALL 	CICLOXREVERSA
	GOTO 	END

;---------------------------CICLOS-------------------------------------
CICLOXREVERSA
	CALL 	CICLOMINIXREVERSA	;REGRESAR TODO EN X PARA NO ENREDAR CABLES
	INCF	COUNTX,1	;COUNTX++
	MOVF	LIMITX, W	;W = LIMITX
	SUBWF	COUNTX, w	;W = LIMITX - COUNTX
	BTFSS	STATUS,Z	;SALTO SI LA RESTA DIO 0
	GOTO	CICLOXREVERSA	;REPETIR HASTA QUE COUNTX = LIMITX
	GOTO 	MAYOR		;TERMINAR EL PROGRAMA
CICLOMINIX
	CALL 	EJEX		;ROTA EN EJE X

	
	;MOVE ON X
	INCF	COUNTMINIX,1	;COUNTMINIX++
	MOVF  	LIMITMINIX, w	;W = LIMITMINIX
	SUBWF 	COUNTMINIX,w	;W = W - COUNTMINIX
	BTFSS 	STATUS,Z 	;SALTO SI LA RESTA DIO CERO
	GOTO 	CICLOMINIX		;REPETIR SI COUNTMINIX !=  LIMITMINIX
	CALL	CICLOY 		;MOVERME EN EJE Y y REGRESAR
	CALL 	LIMPIARMINIX		;COUNTMINIX = 0
	RETURN
CICLOY				
	CALL 	EJEY		;ROTAR EN EL EJE Y
	;C?DIGO PARA COMPARAR Y GUARDAR VALOR DE LA FOTORESISTENCIA-------

	;-----------------------------------------
	;MOVE ON Y
	INCF	COUNTY,1	;COUNTY++ 
	MOVF  	LIMITY, w	;W = LIMITY
	SUBWF 	COUNTY,w	;W = W - COUNTY
	BTFSS 	STATUS,Z	;SALTO SI LA RESTA DIO 0
	GOTO 	CICLOY		;REPETIR SI COUNT !=  LIMITY
	CALL 	LIMPIARY		;COUNTY = 0
	CALL 	CICLOYREVERSA	;REGRESAR Y
	return
CICLOYREVERSA
	CALL 	REVERSEEJEY	;ROTAR EN REVERSA EN EL EJE Y
	INCF	COUNTY,1	;COUNTY++	 
	MOVF  	LIMITY, w	;W = LIMITY
	SUBWF 	COUNTY,w	;W = LIMITY - COUNTY
	BTFSS 	STATUS,Z	;SALTO SI LA RESTA DIO 0
	GOTO 	CICLOYREVERSA	;REPETIR SI COUNTY != LIMITY
	CALL 	LIMPIARY		;COUNTY = 0
	RETURN
CICLOMINIXREVERSA
	CALL 	REVERSEEJEX	;ROTAR EN REVERSA EN EL EJE X
	INCF 	COUNTMINIX,1	;COUNTMINIX++ 
	MOVF  	LIMITMINIX, w	;W = LIMITMINIX
	SUBWF 	COUNTMINIX,w	;W = LIMITMINIX - COUNTMINIX
	BTFSS 	STATUS,Z	;SALTO SI LA RESTA DIO 0
	GOTO 	CICLOMINIXREVERSA	;REPETIR SI COUNTMINIX != LIMITMINIX
	CALL 	LIMPIARMINIX		;COUNTMINIX = 0
	RETURN
;------------------------------RETRASO-------------------------------
RETRASO 			; = 0.0001 segundos
	MOVLW	0xA5	;165
	MOVWF	p1	;pl = 165
ESPERA
	DECFSZ	p1, f	;Decrementar f, saltar si es 0
	GOTO	ESPERA
	RETURN
;-----------LIMPIAR CONTADORES-----------------------------------------------
LIMPIARY
	MOVLW 	0x00  
	MOVWF 	COUNTY  
	RETURN
LIMPIARMINIX
	MOVLW 	0x00  ;se asigna la literal a w (0x00)
	MOVWF 	COUNTMINIX ;muevo w a COUNT 
	RETURN
LIMIPIARX
	MOVLW 	0x00 
	MOVWF 	COUNTX 
	RETURN
;----------------ROTAR EN LOS EJES -----------------------------------------
EJEX
	CALL	MV07
	CALL	MV03
	CALL	MV11
	CALL	MV09
	CALL	MV13
	CALL	MV12
	CALL	MV14
	CALL	MV06
	RETURN
EJEY	
	CALL	MVY7
	CALL	MVY3
	CALL	MVY11
	CALL	MVY9
	CALL	MVY13
	CALL	MVY12
	CALL	MVY14
	CALL	MVY6
	RETURN
REVERSEEJEY
	CALL	MVY6
	CALL	MVY14
	CALL	MVY12
	CALL	MVY13
	CALL	MVY9
	CALL	MVY11	
	CALL	MVY3
	CALL	MVY7
	RETURN
REVERSEEJEX
	CALL  	MV06
	CALL	MV14
	CALL	MV12
	CALL	MV13
	CALL	MV09
	CALL	MV11
	CALL	MV03
	CALL	MV07
	RETURN
;----------------------------MOVIEMIENTOS----------------------------------
MV	
	CALL 	RETRASO		;Retraso de 0.0001 segundos
	MOVF	DATO, W		;W = DATO
	MOVWF	PORTB		;MOVER W AL PUERTO B
	RETURN
MV03
	MOVLW	B'00110000'
	MOVWF	DATO		;DATO = 0|3
	CALL	MV		;MUEVE DATO AL PUERTO B
	RETURN
MV06
	MOVLW	B'01100000'
	MOVWF	DATO		;DATO = 0|6
	CALL	MV		;MUEVE DATO AL PUERTO D
	RETURN
MV07
	MOVLW	B'01110000'
	MOVWF	DATO		;DATO = 0|7
	CALL	MV		;MUEVE DATO AL PUERTO D
	RETURN
MV09
	MOVLW	B'10010000'	;DATO = 0|9
	MOVWF	DATO		;MUEVE DATO AL PUERTO D
	CALL	MV
	RETURN
MV11
	MOVLW 	B'10110000'
	MOVWF	DATO
	CALL	MV
	RETURN	
MV12
	MOVLW	B'11000000'
	MOVWF	DATO		;DATO = 0|12
	CALL	MV		;MUEVE DATO AL PUERTO D
	RETURN
MV13	MOVLW	B'11010000' 
	MOVWF	DATO 
	CALL	MV 
	RETURN

MV14	MOVLW	B'11100000' 
	MOVWF	DATO 
	CALL	MV 
	RETURN

MVY3
	MOVLW	B'00000011'
	MOVWF	DATO		;DATO = 3|0
	CALL	MV		;MUEVE AL PUERTO D
	RETURN
MVY6
	MOVLW	B'00000110'
	MOVWF	DATO		;DATO = 6|0
	CALL	MV		;MUEVE AL PUERTO D
	RETURN
MVY7
	MOVLW	B'00000111'
	MOVWF	DATO		;DATO = 7|0
	CALL	MV		;MUEVE AL PUERTO D
	RETURN
MVY9
	MOVLW	B'00001001'
	MOVWF	DATO		;DATO = 9|0
	CALL	MV		;MUEVE AL PUERTO D
	RETURN
MVY11	
	MOVLW 	B'00001011'
	MOVWF	DATO
	CALL	MV
	RETURN
MVY12
	MOVLW	B'00001100'
	MOVWF	DATO		;DATO = 12|0
	CALL	MV		;MUEVE AL PUERTO D
	RETURN	

MVY13	MOVLW	B'00001101' 
	MOVWF	DATO 
	CALL	MV 
	RETURN

MVY14	MOVLW	B'00001110' 
	MOVWF	DATO 
	CALL	MV 
	RETURN
;-------------------------------------------------------------------------- IR A MAYOR ------------------------
MAYOR




GOTO ETIQUETA
----------------------------------Esperar a que se presione el boton-------------------------------------------
ETIQUETA:
	BTFSC	PORTE,0
	GOTO	COMUNICACION
	GOTO 	ETIQUETA

------------------------------------------------Comunicacion---------------------------------------------------
COMUNICACION




	BTFSC	PORTE,0	
	GOTO	IMPRIMIR
	
GOTO IMPRIMIR

;----------------------------------------IMPRIMIR NUMEROS------------------------------------------------------
IMPRIMIR ;Verificar si presionó el botón, añadir uno al contador.
	BTFSC	PORTE,0	
	CALL	Incrementar
	;Segun el valor de contador, asignar el valor de varE e imprimir
	GOTO	SwitchCont
Incrementar ;CONT++, SI ES MAYOR A 3 SE RESETEA. =========================	
	INCF	cont,1
	BTFSC	cont,2
	CALL	ResetCont
	RETURN
ResetCont
	MOVLW	B'00000000'
	MOVWF	cont
	RETURN
SwitchCont	;Switch con el contador. casos 0,1,2,3 ========================
	BTFSC	cont,0
	GOTO	CI	;Caso Impar
	GOTO	CP	;Caso Par
CP:
	BTFSC	cont,1
	GOTO	case2	;10
	GOTO	case0	;00
CI:
	BTFSC	cont,1
	GOTO	case3	;11
	GOTO	case1	;01
case0:
	MOVFW	varA
	MOVWF	varE
	GOTO	Imprimir
case1:
	MOVFW	varB
	MOVWF	varE
	GOTO	Imprimir
case2:
	MOVFW	varC
	MOVWF	varE
	GOTO	Imprimir
case3:
	MOVLW	B'00000010'
	MOVWF	varE
	GOTO	Imprimir

Imprimir;MUESTRA EN UN DISPLAY EL VALOR DE varE =========================
	;primer bit de entrada de varE
	BTFSC	varE,0
	GOTO	IMPAR;1,3,5,7,9
	GOTO	PAR ;0,2,4,6,8
PAR ;0,2,4,6,8
	;Segundo bit de entrada de varE
	BTFSC	varE,1
	GOTO	PAR4 ;2,6
	GOTO	PAR2 ;0,4,8
	
PAR2 ;0,4,8
	;tercer bit de entrada de C
	BTFSC	varE,2
	GOTO	CUATRO
	GOTO	PAR3 ;0,8
	
PAR3 ;0,8
	;cuarto bit de entrada de C
	BTFSC	varE,3
	GOTO	OCHO
	GOTO	CERO
PAR4 ;2,6
	;tercer bit de entrada de C
	BTFSC	varE,2
	GOTO	SEIS
	GOTO	DOS
IMPAR ;1,3,5,7,9
	;Segundo bit de entrada de C
	BTFSC	varE,1
	GOTO	IMPAR4 ;3,7
	GOTO	IMPAR2 ;1,5,9
IMPAR2 ;1,5,9
	;tercer bit de entrada de C
	BTFSC	varE,2
	GOTO	CINCO
	GOTO	IMPAR3 ;1,9
IMPAR3 ;1,9
	;cuarto bit de entrada de C
	BTFSC	varE,3
	GOTO	NUEVE
	GOTO	UNO
IMPAR4 ;3,7
	;tercer bit de entrada de C
	BTFSC	varE,2
	GOTO	SIETE
	GOTO	TRES	
CERO
	MOVLW	B'00111111'
	MOVWF	PORTD
	GOTO	IMPRIMIR
UNO
	MOVLW	B'00000110'
	MOVWF	PORTD
	GOTO	IMPRIMIR
DOS
	MOVLW	B'01011011'
	MOVWF	PORTD
	GOTO	IMPRIMIR
TRES
	MOVLW	B'01001111'
	MOVWF	PORTD
	GOTO	IMPRIMIR

CUATRO
	MOVLW	B'01100110'
	MOVWF	PORTD
	GOTO	IMPRIMIR
CINCO
	MOVLW	B'01101101'
	MOVWF	PORTD
	GOTO	IMPRIMIR
SEIS
	MOVLW	B'01111101'
	MOVWF	PORTD
	GOTO	IMPRIMIR
SIETE
	MOVLW	B'00000111'
	MOVWF	PORTD
	GOTO	IMPRIMIR

OCHO	
	MOVLW	B'01111111'
	MOVWF	PORTD
	GOTO	IMPRIMIR
NUEVE
	MOVLW	B'01100111'
	MOVWF	PORTD
	GOTO	IMPRIMIR



END
